version: 2.1
commands:
    run_tests:
        steps:
            - run:
                name: Install GCC ARM Embedded
                working_directory: /opt
                command: |
                    dpkg --add-architecture i386
                    apt-get -y update
                    apt-get -y install libc6:i386 libncurses5:i386 libstdc++6:i386
                    wget -O gcc_arm_embedded.tar.bz2 "https://developer.arm.com/-/media/Files/downloads/gnu-rm/5_3-2016q1/gccarmnoneeabi532016q120160330linuxtar.bz2?revision=417e2623-c259-4a12-aacc-c87200b569c7?product=GNU%20Arm%20Embedded%20Toolchain,32-bit,,Linux,5-2016-q1-update"
                    tar -jxf gcc_arm_embedded.tar.bz2
                    echo 'export PATH="/opt/gcc-arm-none-eabi-5_3-2016q1/bin:$PATH"' >> $BASH_ENV
            - run:
                name: Configure Git and Mercurial
                command: |
                    git config --global user.email "test@mbed.org"
                    git config --global user.name "mbed Test"
                    echo -e "[ui]\nusername = mbed Test <test@mbed.org>\n" > ~/.hgrc
            - checkout
            - run:
                name: Install Mbed CLI
                command: |
                    pip install -U pytest setuptools
                    pip install -e .
                    mbed --version
            - run:
                name: Run unit tests
                command: py.test test
            - run:
                name: Configure Mbed CLI for integration tests
                command: |
                    mbed toolchain -G GCC_ARM
                    mbed target -G K64F
                    mbed config -G protocol https
                    mkdir integration_tests
            - run:
                name: Create a new project
                working_directory: integration_tests
                command: mbed new new-test
            - run:
                name: Test project inspection
                working_directory: integration_tests/new-test
                command: |
                    mbed ls
                    mbed releases -r
            - run:
                name: Build through "compile" and "test"
                working_directory: integration_tests/new-test
                command: |
                    echo $PATH
                    ls -l /opt/gcc-arm-none-eabi-5_3-2016q1/bin
                    mbed compile --source=. --source=mbed-os/drivers/tests/TESTS/mbed_drivers/generic_tests -j 0
                    mbed test --compile -n mbed-os-tests-mbed_drivers-generic_tests -j 0

jobs:
    python27:
        docker:
            - image: python:2.7
        steps:
            - run_tests
    python36:
        docker:
            - image: python:3.6
        steps:
            - run_tests
    python37:
        docker:
            - image: python:3.7
        steps:
            - run_tests
workflows:
    version: 2
    build:
        jobs:
            - python27
            - python36
            - python37
